### ISSUE TITLE
GetUserAvailability throws NotImplementedException

### ISSUE THREAD

**Issue by Noximi42** [sherlock1982/ews-managed-api#10]
I'm trying to get the availablility for a room by calling `GetUserAvailability`, but it throws a `NotImplementedException` exception. 

`List<AttendeeInfo> RoomInfo = new List<AttendeeInfo>() { new AttendeeInfo(Rooms[0].Address) };`
`var result = await Service.GetUserAvailability(RoomInfo, new TimeWindow(DateTime.Now.AddDays(-1), DateTime.Now.AddDays(1)), AvailabilityData.FreeBusy)`

It seems to be independent of the email address, used for the `AttenddeeInfo`.
I tryied Nuget package verison 1.0.12 and 1.0.4, as well as targeting different .net core framework version without any success. 
Other methods like `FindAppointments` work without any problems. 

Can some give me an advise to resolve this issues?
Very many thanks in advance.

**Comment by sherlock1982** [comment]
I'm afraid it's intended and I mentioned in in description.
GetUserAvailabilityRequest requires local TimeZone to be send to the server. .NET Standard 1.6 doesn't have timezone API.

Though I wonder what's gonna happen if I send UTC timezone but I haven't tried it yet. 

I use this library to get user availability by syncing with calendar, responding to calendar changes and using Quartz to imitate meeting starts on client. But that's a huge amount of coding. On the other hand it gives me event notifications instead of polling.

**Comment by Noximi42** [comment]
Thanks for your replay.

The new verion .Net Standard 2.0 does support [TimeZone](https://docs.microsoft.com/de-de/dotnet/api/system.timezone?view=netstandard-2.0) as well as [TimeZoneInfo.TransitionTime](https://docs.microsoft.com/de-de/dotnet/api/system.timezoneinfo.transitiontime?view=netstandard-2.0) (which was also missing in .Net Standard 1.6). I already cloned your project and tested the upgrade. The `GetUserAvailablilty` method works (didn't test anything else so far) with .Net Standard 2.0. 

Will you consider an update to .Net Standard 2.0 in your project and your NuGet packages in the foreseeable future? For now I can use my own compiled version, but in order to share my project with other colleagues, it would be easier to share the library via your NuGet package.

**Comment by sherlock1982** [comment]
Yes, I will try to check on Monday
